### ISSUE TITLE
A bunch of errors in the console when running multiple tests

### ISSUE THREAD

**Issue by agzam** [viesti/cypress-clojurescript-preprocessor#14]
I have noticed a weird, mildly annoying problem. For some reason, when running multiple tests, there is a bunch of errors shown in the dev-tools console.

![image](https://user-images.githubusercontent.com/1091022/167745513-82090e6f-c3e3-42c8-9516-5fad89697191.png)

## Repro steps

1. Create multiple test files

    cypress/integration/foo.cljs
    ```clojure
    (ns foo
      (:require-macros [latte.core :refer [describe it]])
      (:require [latte.chai :refer [expect]]))

    (describe "test foo"
      (it "foo test" []
        (expect 0 :to.be.eq 0)))
    ```

    cypress/integration/bar.cljs
    ```clojure
    (ns bar
      (:require-macros [latte.core :refer [describe it]])
      (:require [latte.chai :refer [expect]]))

    (describe "test bar"
      (it "bar test" []
        (expect 0 :to.be.eq 0)))
    ```

2. Open Cypress 

    ```
    $> npx cypress open
    ```

3. Try running individual tests.

    3.1 Click on `foo.cljs` test
    3.2 Once in the browser, toggle the devtools on

    **Observed:** No errors in the devtools console

    3.3 Stop the test
    3.4 Click on `bar.cljs`
    3.5 Once in the browser, toggle the devtools on

    **Observed:** No errors in the devtools console

4. Inside the Cypress App, click "Run 2 integration specs"

    4.1 Once in the browser, toggle the devtools on

    **Observed:** A bunch of error messages

    <details>
    <summary>Detailed log</summary>
    
        cypress_runner.js:201183 Console was cleared
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.debug.Error" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.debug.error.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.debug.error.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1547:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.dom.NodeType" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.dom.nodetype.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1548:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.asserts" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.asserts.asserts.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1549:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.reflect" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.reflect.reflect.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1550:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.math.Long" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.math.long.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.math.long.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1551:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.math.Integer" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.math.integer.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1552:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.dom.asserts" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.dom.asserts.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1553:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.functions" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.functions.functions.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1554:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.string.TypedString" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.string.typedstring.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1555:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.string.Const" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.string.const.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1556:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.i18n.bidi" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.i18n.bidi.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1557:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.trustedtypes" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.html.trustedtypes.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1558:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.SafeScript" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.html.safescript.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.html.safescript.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1559:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.fs.url" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.fs.url.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1560:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.fs.blob" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.fs.blob.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1561:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.TrustedResourceUrl" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.html.trustedresourceurl.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1562:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.string.internal" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.string.internal.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1563:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.SafeUrl" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.html.safeurl.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1564:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.SafeStyle" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.html.safestyle.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.html.safestyle.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1565:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.object" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.object.object.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.object.object.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1566:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.SafeStyleSheet" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.html.safestylesheet.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.html.safestylesheet.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1567:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.dom.HtmlElement" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.dom.htmlelement.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1568:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.dom.TagName" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.dom.tagname.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1569:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.array" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.array.array.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.array.array.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1570:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.labs.userAgent" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.labs.useragent.useragent.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.labs.useragent.useragent.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1571:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.labs.userAgent.util" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.labs.useragent.util.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.labs.useragent.util.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1572:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.labs.userAgent.browser" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.labs.useragent.browser.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.labs.useragent.browser.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1573:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.dom.tags" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.dom.tags.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1574:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.SafeHtml" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.html.safehtml.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.html.safehtml.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1575:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.html.uncheckedconversions" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.html.uncheckedconversions.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1576:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.dom.safe" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.dom.safe.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1577:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.string" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.string.string.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1578:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.collections.maps" already declared.
            at Object.goog.module (tests?p=cypress/integration/foo.cljs:106:13)
            at eval (goog.collections.maps.js:3:8)
            at Object.goog.loadModule (tests?p=cypress/integration/foo.cljs:281:27)
            at eval (goog.collections.maps.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1579:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.structs" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.structs.structs.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1580:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.uri.utils" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.uri.utils.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1581:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.Uri" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.uri.uri.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1582:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "goog.string.StringBuffer" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (goog.string.stringbuffer.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1583:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "cljs.core" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (cljs.core.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1584:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "clojure.string" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (clojure.string.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1585:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "shadow.cljs.devtools.client.console" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (shadow.cljs.devtools.client.console.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1586:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "clojure.set" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (clojure.set.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1587:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "kit.core" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (kit.core.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1588:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "latte.add" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (latte.add.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1589:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "latte.overwrite" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (latte.overwrite.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1590:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        tests?p=cypress/integration/foo.cljs:1425 Error: Namespace "latte.chai" already declared.
            at Object.goog.provide (tests?p=cypress/integration/foo.cljs:62:13)
            at eval (latte.chai.js:1:6)
            at eval (<anonymous>)
            at Object.goog.globalEval (tests?p=cypress/integration/foo.cljs:472:11)
            at Object.env.evalLoad (tests?p=cypress/integration/foo.cljs:1533:12)
            at eval (tests?p=cypress/integration/foo.cljs:1591:12)
            at eval (<anonymous>)
        reportError @ tests?p=cypress/integration/foo.cljs:1425
        :3001/__/#/tests/__all:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:3001/__cypress/runner/fonts/fa-regular-400.woff2

    </details>

**Comment by viesti** [comment]
Urgh,  I think did try the "run all specs", but didn't notice this :/

I'm not sure but [output-wrapper](https://shadow-cljs.github.io/docs/UsersGuide.html#output-wrapper) comes to mind. It might be that when all specs are loaded into same window in the Cypress runner, shared global names collide. 

Not sure how to fix this yet. Tried adding 

```clojure
:compiler-options {:output-wrapper true
                      :rename-prefix-namespace "<something unique for each build>"}
```
but that didn't seem to change the output. Hmm...
